### ISSUE TITLE
Incorrect reference to @behaviour OIDC.Auth.ClientConfig in documentation

### ISSUE THREAD

**Issue by brianmay** [tanguilp/plugoid#10]
As far as I can tell, `OIDC.Auth.ClientConfig` doesn't exist, and I am not sure I see what it should be referring to.

**Comment by brianmay** [comment]
I now believe `OIDC.ClientConfig` is correct.

**Comment by tanguilp** [comment]
It's another library - `oidc`. Is it fixed? If so, feel free to close the issue.

**Comment by brianmay** [comment]
The error is here: https://hexdocs.pm/plugoid/0.1.0/quickstart.html#step-4-create-a-client-callback

**Comment by tanguilp** [comment]
Fixed, thanks for reporting (was `OIDC.ClientConfig`).
