### ISSUE TITLE
internal Server Error when logging in

### ISSUE THREAD

**Issue by brianmay** [tanguilp/plugoid#13]
Yesterday, I noticed - immediately after valid login - I was getting redirected to pages such as https://.../page?oidc_error=?

Which in turn was producing "Internal Server Error". I don't have the logs unfortunately. And I cannot reproduce this yet today.

But if I do go to the same page today I see:

```
20:38:48.148 [error] #PID<0.2930.0> running RoboticaFaceWeb.Endpoint (connection #PID<0.2920.0>, stream id 15) terminated
Server: brian.robotica.pri:443 (https)
Request: GET /local?oidc_error=[....]
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, :invalid}
        (plugoid 0.4.3) lib/plugoid.ex:431: Plugoid.call/2
        (robotica_face 0.1.0) RoboticaFaceWeb.Router.ensure_auth/2
        (robotica_face 0.1.0) lib/robotica_face_web/router.ex:1: RoboticaFaceWeb.Router.__pipe_through2__/1
        (phoenix 1.6.2) lib/phoenix/router.ex:347: Phoenix.Router.__call__/2
        (robotica_face 0.1.0) lib/robotica_face_web/endpoint.ex:1: RoboticaFaceWeb.Endpoint.plug_builder_call/2
        (robotica_face 0.1.0) lib/robotica_face_web/endpoint.ex:1: RoboticaFaceWeb.Endpoint.call/2
        (phoenix 1.6.2) lib/phoenix/endpoint/cowboy2_handler.ex:43: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.9.0) /home/brian/tree/personal/relixir/robotica/robotica_nerves/deps/rpi3/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
```

I am not sure what was causing the original error: maybe something specific to Firefox on mobile? The token should not have been expired or invalid, as I was repeatedly authenticating, and it looked like the authentication worked. Will see if I can reproduce this again.

However it does look like the code needs to be able to handle `{:error, _}` tuples from the call to verify on line 431.

**Comment by tanguilp** [comment]
You're using the conn_callback branch, aren't you? IF so the error is at https://github.com/tanguilp/plugoid/blob/conn_callback/lib/plugoid.ex#L431

Question: have you set the SECRET_KEY_BASE in Phoenix? This line shouldn't fail if correctly configured.

**Comment by brianmay** [comment]
Yes, that is correct.

Yes, Phoenix is correctly configured.

So far not seen that error again. Will keep trying to reproduce it.

**Comment by tanguilp** [comment]
Might be wrong copy/pasting of the URL with missing end of it?

**Comment by brianmay** [comment]
Nope. Was just using the website normally, and then I came back to it and it kept saying Internal Server Error. Was wondering if it was something to do with session expiry. But now I can't reproduce it. Weird.

One possibility that I haven't been able to rule out is that an error occurred decoding the token, which then sent a redirect:

**Comment by tanguilp** [comment]
Was thinking about expiration too. That said I think the code is correct, this situation should not happen and when it fails it means that something very wrong happened :)

**Comment by brianmay** [comment]
I am going to close this for now.
