### ISSUE TITLE
Try to get authentication but continue as unauthenticated

### ISSUE THREAD

**Issue by brianmay** [tanguilp/plugoid#9]
I commonly have a `/` page that shows a brief introduction to the website, and then allows the user to login if they aren't already logged. To do this, I generally use two pipelines:

* auth:  try to get authentication details if possible, otherwise continue as anonymous user.
* ensure_auth: same as auth, but redirect user to login page if anonymous user.

Would be good if there was some way of doing this with plugoid.

**Comment by tanguilp** [comment]
You want to use the `on_unauthenticated` option (https://hexdocs.pm/plugoid/Plugoid.html#module-additional-plug-options).

Example in `plugoid_demo`: https://github.com/tanguilp/plugoid_demo/blob/master/lib/plugoid_demo_web/router.ex#L34

**Comment by brianmay** [comment]
Yes, looks like that does it. Thanks
